# Generated by Django 5.2.4 on 2025-07-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='processing_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
